[package]
name = "deciduously-com"
version = "0.2.0"
authors = ["deciduously <github@deciduously.com>"]

[dependencies]

actix = "0.5"
actix-web = "0.6"
env_logger = "0.5"
lazy_static = "1.0"
pulldown-cmark = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
tera = "0.11"